# Generated by Django 5.0.7 on 2025-03-26 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventory', '0002_initial'),
        ('Reserves', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Id del Cliente'),
        ),
        migrations.AddField(
            model_name='reserve',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='Reserves.event'),
        ),
        migrations.AddField(
            model_name='reserve',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.sale', verbose_name='Id de la Venta'),
        ),
    ]
