# Generated by Django 5.0.7 on 2025-03-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Reserves", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserve",
            name="num_people",
            field=models.IntegerField(default=1, verbose_name="Número de Personas"),
        ),
    ]
