# Generated by Django 5.0.7 on 2025-03-26 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventory', '0001_initial'),
        ('Prizes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productshistory',
            name='by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Encargado'),
        ),
        migrations.AddField(
            model_name='productshistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='sale',
            name='by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='by', to=settings.AUTH_USER_MODEL, verbose_name='Encargado'),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Id del Cliente'),
        ),
        migrations.AddField(
            model_name='productshistory',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.sale', verbose_name='Venta Relacionada'),
        ),
        migrations.AddField(
            model_name='saleprizes',
            name='prize',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prizes.prizes'),
        ),
        migrations.AddField(
            model_name='saleprizes',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='Inventory.sale'),
        ),
        migrations.AddField(
            model_name='saleproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.product'),
        ),
        migrations.AddField(
            model_name='saleproduct',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Inventory.sale'),
        ),
    ]
