# Generated by Django 5.0.7 on 2025-03-28 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Inventory", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="offered_price",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Precio de oferta"
            ),
        ),
    ]
