# Generated by Django 5.0.7 on 2025-03-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Inventory", "0004_saleproduct_unit_price_offered"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saleproduct",
            name="unit_price",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Precio Unitario"
            ),
        ),
        migrations.AlterField(
            model_name="saleproduct",
            name="unit_price_offered",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Precio Unitario Ofertado"
            ),
        ),
    ]
