# Generated by Django 5.0.7 on 2025-03-28 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Inventory", "0005_alter_saleproduct_unit_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="saleproduct",
            name="unit_price_offered",
        ),
    ]
