# Generated by Django 5.0.7 on 2025-03-28 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Inventory", "0006_remove_saleproduct_unit_price_offered"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleproduct",
            name="is_offer",
            field=models.BooleanField(default=False, verbose_name="Producto en oferta"),
        ),
    ]
